// Code generated by "stringer -type=HealingDriveReason -output=heal-commands-drive-reason_gen.go -trimprefix=HealingReason heal-commands.go"; DO NOT EDIT.

package madmin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HealingReasonFreshDisk-0]
	_ = x[HealingReasonOfflineDisk-1]
	_ = x[HealingReasonSkewedDisk-2]
}

const _HealingDriveReason_name = "FreshDiskOfflineDiskSkewedDisk"

var _HealingDriveReason_index = [...]uint8{0, 9, 20, 30}

func (i HealingDriveReason) String() string {
	if i < 0 || i >= HealingDriveReason(len(_HealingDriveReason_index)-1) {
		return "HealingDriveReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HealingDriveReason_name[_HealingDriveReason_index[i]:_HealingDriveReason_index[i+1]]
}
